create table if not exists public.transaction_catalogs (
    id bigserial primary key,
    financial_scope text not null check (financial_scope in ('pf', 'pj')),
    transaction_type text not null check (transaction_type in ('income', 'expense', 'investment')),
    category text not null,
    subcategory text not null,
    sort_order integer not null default 0,
    created_at timestamptz not null default timezone('utc', now()),
    unique (financial_scope, transaction_type, category, subcategory)
);

delete from public.transaction_catalogs
where financial_scope = 'pf'
  and transaction_type = 'expense'
  and (
    (category = 'contas' and lower(subcategory) like '%stream%')
    or category = 'streaming'
  );

insert into public.transaction_catalogs (financial_scope, transaction_type, category, subcategory, sort_order) values
('pf','expense','alimentacao','Lanche',10),
('pf','expense','alimentacao','Almoço',11),
('pf','expense','alimentacao','Café',12),
('pf','expense','alimentacao','Janta',13),
('pf','expense','alimentacao','Delivery',14),
('pf','expense','alimentacao','Restaurante',15),
('pf','expense','alimentacao','Bar',16),
('pf','expense','alimentacao','Supermercado',17),
('pf','expense','transporte','Uber',20),
('pf','expense','transporte','99',21),
('pf','expense','transporte','Combustível',22),
('pf','expense','transporte','Passagem',23),
('pf','expense','transporte','Metrô',24),
('pf','expense','transporte','Pedágio',25),
('pf','expense','transporte','Estacionamento',26),
('pf','expense','automovel','Lavagem',30),
('pf','expense','automovel','Manutenção',31),
('pf','expense','automovel','Conserto',32),
('pf','expense','automovel','Seguro',33),
('pf','expense','automovel','IPVA',34),
('pf','expense','automovel','Pneu',35),
('pf','expense','automovel','Revisão',36),
('pf','expense','contas','Conta de luz',40),
('pf','expense','contas','Conta de água',41),
('pf','expense','contas','Internet',42),
('pf','expense','contas','Telefone',43),
('pf','expense','contas','Gás',44),
('pf','expense','streaming','Netflix',50),
('pf','expense','streaming','Prime Video',51),
('pf','expense','streaming','Disney+',52),
('pf','expense','streaming','Max',53),
('pf','expense','streaming','Spotify',54),
('pf','expense','streaming','YouTube Premium',55),
('pf','expense','streaming','Apple Music',56),
('pf','expense','streaming','Globoplay',57),
('pf','expense','moradia','Aluguel',60),
('pf','expense','moradia','Condomínio',61),
('pf','expense','moradia','Reforma',62),
('pf','expense','moradia','Móveis',63),
('pf','expense','moradia','Decoração',64),
('pf','expense','lazer','Cinema',70),
('pf','expense','lazer','Show',71),
('pf','expense','lazer','Viagem',72),
('pf','expense','lazer','Passeio',73),
('pf','expense','lazer','Presente',74),
('pf','expense','lazer','Academia',75),
('pf','expense','saude','Consulta',80),
('pf','expense','saude','Exame',81),
('pf','expense','saude','Farmácia',82),
('pf','expense','saude','Plano de saúde',83),
('pf','expense','saude','Dentista',84),
('pf','expense','saude','Terapia',85),
('pf','expense','educacao','Curso',90),
('pf','expense','educacao','Mensalidade',91),
('pf','expense','educacao','Livro',92),
('pf','expense','educacao','Material escolar',93),
('pf','expense','educacao','Certificação',94),
('pf','income','salario','Salário mensal',100),
('pf','income','salario','Adiantamento',101),
('pf','income','salario','Comissão',102),
('pf','income','freelance','Projeto freelance',110),
('pf','income','freelance','Consultoria',111),
('pf','income','freelance','Serviço avulso',112),
('pf','income','freelance','Pagamento de cliente',113),
('pf','income','vendas','Venda online',120),
('pf','income','vendas','Marketplace',121),
('pf','income','vendas','Venda de produto',122),
('pf','income','vendas','Revenda',123),
('pf','income','bonus','Bônus',130),
('pf','income','bonus','Premiação',131),
('pf','income','bonus','Participação nos lucros',132),
('pf','investment','investimentos','Aporte',140),
('pf','investment','investimentos','Cofrinho',141),
('pf','investment','investimentos','Corretagem',142),
('pf','investment','investimentos','Taxa',143),
('pf','investment','investimentos','Compra de ativo',144),
('pj','expense','operacional','Internet empresa',200),
('pj','expense','operacional','Energia',201),
('pj','expense','operacional','Software',202),
('pj','expense','operacional','Assinatura SaaS',203),
('pj','expense','operacional','Escritório',204),
('pj','expense','fornecedores','Compra de insumo',210),
('pj','expense','fornecedores','Pagamento fornecedor',211),
('pj','expense','fornecedores','Terceirizado',212),
('pj','expense','fornecedores','Matéria-prima',213),
('pj','expense','impostos','DAS',220),
('pj','expense','impostos','Simples Nacional',221),
('pj','expense','impostos','ISS',222),
('pj','expense','impostos','Taxa bancária',223),
('pj','expense','impostos','Contabilidade',224),
('pj','expense','marketing','Anúncio',230),
('pj','expense','marketing','Tráfego pago',231),
('pj','expense','marketing','Designer',232),
('pj','expense','marketing','Impulsionamento',233),
('pj','expense','marketing','CRM',234),
('pj','expense','tecnologia','Hospedagem',240),
('pj','expense','tecnologia','Domínio',241),
('pj','expense','tecnologia','Ferramenta',242),
('pj','expense','tecnologia','Licença',243),
('pj','expense','tecnologia','API',244),
('pj','expense','equipe','Pró-labore',250),
('pj','expense','equipe','Comissão',251),
('pj','expense','equipe','Freela',252),
('pj','expense','equipe','Benefício',253),
('pj','expense','equipe','Folha',254),
('pj','expense','deslocamento','Uber empresa',260),
('pj','expense','deslocamento','Combustível',261),
('pj','expense','deslocamento','Pedágio',262),
('pj','expense','deslocamento','Viagem',263),
('pj','expense','estrutura','Aluguel comercial',270),
('pj','expense','estrutura','Móveis',271),
('pj','expense','estrutura','Reforma',272),
('pj','expense','estrutura','Material',273),
('pj','income','vendas','Venda online',300),
('pj','income','vendas','Marketplace',301),
('pj','income','vendas','Venda de produto',302),
('pj','income','vendas','Revenda',303),
('pj','income','servicos','Projeto entregue',310),
('pj','income','servicos','Consultoria',311),
('pj','income','servicos','Mensalidade',312),
('pj','income','servicos','Cliente recorrente',313),
('pj','income','contratos','Contrato anual',320),
('pj','income','contratos','Renovação',321),
('pj','income','contratos','Parceria',322),
('pj','income','recorrencia','Assinatura mensal',330),
('pj','income','recorrencia','Plano recorrente',331),
('pj','income','recorrencia','Mensalidade',332),
('pj','income','reembolso','Reembolso de cliente',340),
('pj','income','reembolso','Reembolso bancário',341),
('pj','investment','caixa','Aplicar no caixa',350),
('pj','investment','caixa','Reserva operacional',351),
('pj','investment','expansao','Capital de giro',360),
('pj','investment','expansao','Expansão da empresa',361),
('pj','investment','expansao','Nova unidade',362),
('pj','investment','equipamentos','Notebook',370),
('pj','investment','equipamentos','Monitor',371),
('pj','investment','equipamentos','Impressora',372),
('pj','investment','equipamentos','Cadeira',373),
('pj','investment','reserva','Reserva de emergência PJ',380),
('pj','investment','reserva','Caixa estratégico',381)
on conflict (financial_scope, transaction_type, category, subcategory) do update
set sort_order = excluded.sort_order;
